package main

// ResearchPlan represents the structured research questions determined by the agent.
type ResearchPlan struct {
	QuestionType string   `json:"question_type"`
	Questions    []string `json:"questions"`
}

// Source represents an authoritative reference backing an answer.
type Source struct {
	Title string `json:"title"`
	URL   string `json:"url,omitempty"`
}

// Answer represents the structured, source-backed answer generated by Proto.
type Answer struct {
	Summary  string   `json:"summary"`
	Answer   string   `json:"answer"`
	Guidance []string `json:"guidance,omitempty"`
	Sources  []Source `json:"sources"`
}

// KnowledgeResult represents a single entry retrieved from the Sanity Knowledge Base.
type KnowledgeResult struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Source  string `json:"source"`
}

// Finding represents an individual API design observation or violation.
type Finding struct {
	Severity    string   `json:"severity"`
	Issue       string   `json:"issue"`
	Explanation string   `json:"explanation"`
	Guidance    []string `json:"guidance"`
	Suggestion  string   `json:"suggestion"`
}

// ReviewResult encapsulates the full analysis of the API request.
type ReviewResult struct {
	Summary  string    `json:"summary"`
	Findings []Finding `json:"findings"`
	Sources  []string  `json:"sources"`
}

// APIRequest represents the parsed components of an incoming curl command.
type APIRequest struct {
	Method  string            `json:"method"`
	URL     string            `json:"url"`
	Path    string            `json:"path"`
	Headers map[string]string `json:"headers"`
	Body    string            `json:"body"`
}

// Config holds runtime configuration loaded from environment or .env file.
type Config struct {
	SanityMCPURL    string
	SanityToken     string
	OpenRouterKey   string
	OpenRouterModel string
}
